security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_forward: true
                default_target_path: /
                always_use_default_target_path: true
                username_parameter: _email
                password_parameter: _password
                target_path_parameter: login_success
                failure_path_parameter: login_fail
            logout:
                path: /logout
                target: /logingit 
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: ROLE_ADMIN }
