old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        mail:
            connection: default
            exchange_options: { name: 'mailer', type: topic }
