old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        mail:
            connection: default
            exchange_options: { name: 'dev_mailer_mail', type: direct }
            queue_options:    { name: 'dev_mailer_mail', routing_keys: ['mailer'] }


